name: Makefile CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    # 22.04 (-latest at the time) was too old
    # can switch to -latest once 24.04 is -latest
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install g++-mingw-w64-x86-64-win32 binutils-mingw-w64-x86-64 make

    - name: Build
      run: make

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          real.exe
          real-console.exe
